### PR TITLE
Swagger definition

### LINKED ISSUE #13: Create OpenAPI spec for forest client API

### PR DESCRIPTION
**Pull request by ConradBoydElliottGustafson**
OK, I don't think we should actually merge this into main yet (it's not working code!). I just want to try out the PR function in ZenHub and see how it works. It's been a while since I used it.

In theory, "closes #13" should link the PR to the issue in GitHub and maybe show up on the ZenHub board. In theory, when the PR is merged into the main branch, the issue is closed. See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Of course, communism works "in theory" as well. ;-)

### CODE REVIEW

**Comment by DerekRoberts** [comment]
@ConradBoydElliottGustafson LOL at communism!  Way to go for community engagement.  ;)

I like retaining pretty much everything for reference, even if we remove it later.  Maybe pick a better directory than ./src and we merge?

**Review by DerekRoberts — CHANGES_REQUESTED** [review]
Please pick a different path than ./src.  How about ./ref or ./doc?

**Comment by franTarkenton** [comment]
Is it possible to automate the generation of the go code.  If so could it be the first use of @DerekRoberts pipeline.  Start with openapi spec, generate a docker image in the GHCR with the go code in it.  Deploy it to openshift?

**Comment by DerekRoberts** [comment]
@ConradBoydElliottGustafson Please don't maintain long running branches!  That sort of thing can be retained in a wiki or <shudder/barf> Constipance.

@franTarkenton If that's useful, sure!  (BTW there is already fair bit in the pipeline.)

**Review by franTarkenton — APPROVED** [review]
Just adding to my previous comment!  Sooo I think that all the code in the folder 'go' is automatically generated by, something like `swagger-codegen generate -i ./src/api/swagger.yaml -l go -o ./src/go/`. 

So thinking we could add another stage to the dockerfile that runs the swagger-codegen.

Just a thought.  Likely I'm misunderstanding something or making this more complex then it needs to be! :)

**Comment by ConradBoydElliottGustafson** [comment]
@DerekRoberts +1 to not having long-running branches. I will kill the branch when it is no longer useful.
@franTarkenton +1 to having the pipeline do the generation -- although checking in the generated code might be easier for devs to clone and run something.

**Comment by DerekRoberts** [comment]
@ConradBoydElliottGustafson Commit whatever, we'll do a cleanup when there's an actual app.  Same request though - not in src!

**Comment by ConradBoydElliottGustafson** [comment]
Killing this PR and deleting the branch. Will do better next time!

**Pull request closed without merging**
